fun main()
{
    var salesPercent = 0.62
    var salesThisYear = 4600000
    var salesGenerated = salesPercent*salesThisYear
    println("Projected sales generated by East Coast this year:\n $salesPercent% of $salesThisYear is $$salesGenerated.")
}